- name: Create web security group
  ec2_group:
    name: web
    state: present
    description: security group for web
    vpc_id: "{{ vpc_net.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0

- name: Create ssh security group
  ec2_group:
    name: ssh
    state: present
    description: security group for ssh
    vpc_id: "{{ vpc_net.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
