AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LatestAmiId:
    Type : AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  
  Instance :
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      KeyName: sotosugi
      SecurityGroupIds: 
        - !ImportValue WebSecurityGroup
        - !ImportValue SshSecurityGroup
      SubnetId: !ImportValue PublicSubnet1
      Tags: 
        - Key: Name
          Value: web-cfn
      UserData: !Base64 |
        #!/bin/bash
        yum install -y httpd
        systemctl start httpd.service
        systemctl enable httpd.service
