AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VPCStack:
    Type: String
    Default: MyVPCStack
  SecurityGroupStack:
    Type: String
    Default: MySecurityGroupStack
  KeyName:
    Type: String
    Default: sotosugi
  InstanceType:
    Type: String
    Default: t3.micro

  LatestAmiId:
    Type : AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

  Instance :
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - {"Fn::ImportValue": !Sub "${SecurityGroupStack}-WebSecurityGroup"}
        - {"Fn::ImportValue": !Sub "${SecurityGroupStack}-SSHSecurityGroup"}
      SubnetId: {"Fn::ImportValue": !Sub "${VPCStack}-PublicSubnet1"}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Instance
      UserData: !Base64 |
        #!/bin/bash
        yum install -y httpd
        systemctl start httpd.service
        systemctl enable httpd.service
